development: &default
  base_url: https://cloud.iexapis.com/v1/
  mapping_max_age: <%= 1.month %>
  symbol_lists:
    - ref-data/mutual-funds/symbols
    - ref-data/region/DE/symbols
    - ref-data/region/FR/symbols
    - ref-data/region/GB/symbols
    - ref-data/region/NL/symbols
    - ref-data/otc/symbols
    - ref-data/symbols

test:
  <<: *default
